export const GENERATION_START = "GENERATION_START";
export const GENERATION_FINISH = "GENERATION_FINISH";
export const GENERATION_LINK_FINISH = "GENERATION_LINK_FINISH";
export const GENERATION_LINK_FAILED = "GENERATION_LINK_FAILED";
export const GENERATION_LINK_START = "GENERATION_LINK_START";
export const GENERATION_LINKS_TEXT_UPDATE = "GENERATION_LINKS_TEXT_UPDATE";
export const INITIALIZE_LINK_LIST_COMMUNICATION =
  "INITIALIZE_LINK_LIST_COMMUNICATION";
export const LINK_LIST_CHANGE = "LINK_LIST_CHANGE";
