export const UPLOAD_START = "UPLOAD_START";
export const UPLOAD_FINISH = "UPLOAD_FINISH";
export const FILE_UPLOAD_FINISHED = "FILE_UPLOADED";
export const FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED";
export const FILE_UPLOAD_STARTED = "FILE_UPLOAD_STARTED";
export const INITIALIZE_UPLOAD_COMMUNICATION =
  "INITIALIZE_UPLOAD_COMMUNICATION";
